/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.equipo7.presentacion.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 * Frame de inicio de sesion del sistema y punto de partida del mismo
 * @author neri
 */
public class IniciarSesionDlg extends javax.swing.JDialog {

    /**
     * indica si despues de cerrar el dialogo el usuario puede acceder a la aplicacion
     */
    private boolean validado = false;
    
    /**
     * Creates new form IniciarSesionDlg
     */
    public IniciarSesionDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        FlatDarkLaf.setup();
        initComponents();
        
        this.setTitle("inicio de Sesion");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(0x10, 0x10, 0x10));
        
        this.prepararEstilo();
        this.prepararFuentes();
    }
    
    /**
     * Asigna las fuentes de letra correspondientes a los distintos componentes
     * del dialogo de inicio de sesion
     */
    private void prepararFuentes() {
        this.getContentPane().setFont(new Font("Gotham Light", Font.PLAIN, 12));
        this.contrasenaLbl.setFont(new Font("Gotham Black", Font.PLAIN, 12));
        this.tituloIniciarSesion.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        this.iniciarSesionBtn.setFont(new Font("Gotham Black", Font.PLAIN, 12));
        //this.emailTextField.setFont(new Font("Gotham Black", Font.PLAIN, 12));
        this.correoLbl.setFont(new Font("Gotham Black", Font.PLAIN, 12));
    }
    
    /**
     * Carga los ultimos ajustes de estilo del sistema
     */
    private void prepararEstilo() {
        //UIManager.put("Button.arc", 999);
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloIniciarSesion = new javax.swing.JLabel();
        contrasenaLbl = new javax.swing.JLabel();
        correoLbl = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        iniciarSesionBtn = new javax.swing.JButton();
        contrasenaTextField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        crearCuentaBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tituloIniciarSesion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 28)); // NOI18N
        tituloIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion.setText("Iniciar Sesión");

        contrasenaLbl.setForeground(new java.awt.Color(255, 255, 255));
        contrasenaLbl.setText("Contraseña");

        correoLbl.setForeground(new java.awt.Color(255, 255, 255));
        correoLbl.setText("Correo electronico");

        iniciarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionBtn.setText("Iniciar Sesión");
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });

        contrasenaTextField.setText("jPasswordField1");

        jSeparator1.setBackground(new java.awt.Color(230, 230, 230));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿No tienes una cuenta? ");

        crearCuentaBtn.setForeground(new java.awt.Color(174, 93, 255));
        crearCuentaBtn.setText("Crear cuenta");
        crearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(tituloIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contrasenaLbl)
                            .addComponent(correoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contrasenaTextField)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crearCuentaBtn)))))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(correoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tituloIniciarSesion)
                .addGap(93, 93, 93)
                .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contrasenaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(crearCuentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(correoLbl)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void crearCuentaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMouseClicked
        System.out.println("SHESH");
    }//GEN-LAST:event_crearCuentaBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contrasenaLbl;
    private javax.swing.JPasswordField contrasenaTextField;
    private javax.swing.JLabel correoLbl;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JLabel crearCuentaBtn;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tituloIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
