/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.equipo7.presentacion.gui;

import static Recursos.imageUploader.loadImageWithFileChooser;
import com.equipo7.negocio.bo.UsuariosBO;
import com.equipo7.negocio.bo.interfaces.IUsuariosBO;
import com.equipo7.negocio.dtos.UsuarioDTO;
import com.equipo7.negocio.excepciones.BOException;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author gaspa
 */
public class RegistrarUsuarioDlg extends javax.swing.JDialog {

    private IUsuariosBO usuariosBO = UsuariosBO.getInstance();
    private byte[] imageBytes = null;

    /**
     * Creates new form RegistrarUsuarioDlg
     */
    public RegistrarUsuarioDlg() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tituloIniciarSesion = new javax.swing.JLabel();
        tituloIniciarSesion1 = new javax.swing.JLabel();
        nombreUsuarioTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        tituloIniciarSesion2 = new javax.swing.JLabel();
        tituloIniciarSesion3 = new javax.swing.JLabel();
        tituloIniciarSesion4 = new javax.swing.JLabel();
        tituloIniciarSesion5 = new javax.swing.JLabel();
        terminosCheckBox = new javax.swing.JCheckBox();
        crearCuentaBtn = new javax.swing.JButton();
        contrasenaPasswordField = new javax.swing.JPasswordField();
        confirmContrasenaPasswordField = new javax.swing.JPasswordField();
        subirImagenBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        iconTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 29, 29));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloIniciarSesion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion.setText("Nombre de Usuario");
        jPanel2.add(tituloIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        tituloIniciarSesion1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 28)); // NOI18N
        tituloIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion1.setText("Registrar Cuenta");
        jPanel2.add(tituloIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, -1, -1));

        nombreUsuarioTextField.setBackground(new java.awt.Color(51, 51, 51));
        nombreUsuarioTextField.setColumns(50);
        nombreUsuarioTextField.setForeground(new java.awt.Color(204, 204, 204));
        nombreUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreUsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 304, 40));

        correoTextField.setBackground(new java.awt.Color(51, 51, 51));
        correoTextField.setColumns(50);
        correoTextField.setForeground(new java.awt.Color(204, 204, 204));
        correoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 304, 40));

        tituloIniciarSesion2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion2.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion2.setText("Correo Electronico");
        jPanel2.add(tituloIniciarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        tituloIniciarSesion3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion3.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion3.setText("Imagen de perfil (opcional)");
        jPanel2.add(tituloIniciarSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        tituloIniciarSesion4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion4.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion4.setText("Contraseña");
        jPanel2.add(tituloIniciarSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 720, -1, -1));

        tituloIniciarSesion5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion5.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion5.setText("Confirmar Contraseña");
        jPanel2.add(tituloIniciarSesion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 800, -1, -1));

        terminosCheckBox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        terminosCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        terminosCheckBox.setText("Acepto los terminos y condiciones");
        terminosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminosCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(terminosCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 880, -1, -1));

        crearCuentaBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearCuentaBtn.setText("Crear Cuenta");
        crearCuentaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaBtnActionPerformed(evt);
            }
        });
        jPanel2.add(crearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 910, 304, 30));

        contrasenaPasswordField.setBackground(new java.awt.Color(51, 51, 51));
        contrasenaPasswordField.setColumns(50);
        jPanel2.add(contrasenaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 750, 300, 40));

        confirmContrasenaPasswordField.setBackground(new java.awt.Color(51, 51, 51));
        confirmContrasenaPasswordField.setColumns(50);
        jPanel2.add(confirmContrasenaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 830, 300, 40));

        subirImagenBtn.setText("Subir Imagen");
        subirImagenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirImagenBtnActionPerformed(evt);
            }
        });
        jPanel2.add(subirImagenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, 110, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pexels-photo-374046.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        iconTextLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        iconTextLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(iconTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextFieldActionPerformed

    private void correoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTextFieldActionPerformed

    private void terminosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminosCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminosCheckBoxActionPerformed

    private void crearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaBtnActionPerformed
        if(imageBytes!=null){
            UsuarioDTO usuario = new UsuarioDTO(nombreUsuarioTextField.getText(), correoTextField.getText(), imageBytes.toString(),contrasenaPasswordField.getPassword().toString());
            try {
                usuariosBO.registrarUsuario(usuario);
            } catch (BOException ex) {
                Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            UsuarioDTO usuario = new UsuarioDTO(nombreUsuarioTextField.getText(), correoTextField.getText(), contrasenaPasswordField.getPassword().toString());
            try {
                usuariosBO.registrarUsuario(usuario);
            } catch (BOException ex) {
                Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_crearCuentaBtnActionPerformed

    private void subirImagenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirImagenBtnActionPerformed
        imageBytes = loadImageWithFileChooser();
        if (imageBytes != null) {
                ImageIcon imageIcon = new ImageIcon(imageBytes);
                Image image = imageIcon.getImage().getScaledInstance(iconTextLabel.getWidth(), iconTextLabel.getHeight(), Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(image);
                iconTextLabel.setIcon(imageIcon);
            } else {
                System.out.println("No se selecciono ninguna imagen");
            }
    }//GEN-LAST:event_subirImagenBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmContrasenaPasswordField;
    private javax.swing.JPasswordField contrasenaPasswordField;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JButton crearCuentaBtn;
    private javax.swing.JLabel iconTextLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreUsuarioTextField;
    private javax.swing.JButton subirImagenBtn;
    private javax.swing.JCheckBox terminosCheckBox;
    private javax.swing.JLabel tituloIniciarSesion;
    private javax.swing.JLabel tituloIniciarSesion1;
    private javax.swing.JLabel tituloIniciarSesion2;
    private javax.swing.JLabel tituloIniciarSesion3;
    private javax.swing.JLabel tituloIniciarSesion4;
    private javax.swing.JLabel tituloIniciarSesion5;
    // End of variables declaration//GEN-END:variables
}
