/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.equipo7.presentacion.gui;

/**
 *
 * @author gaspa
 */
public class RegistrarUsuarioDlg extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarUsuarioDlg
     */
    public RegistrarUsuarioDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tituloIniciarSesion = new javax.swing.JLabel();
        tituloIniciarSesion1 = new javax.swing.JLabel();
        nombreUsuarioTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        tituloIniciarSesion2 = new javax.swing.JLabel();
        tituloIniciarSesion3 = new javax.swing.JLabel();
        contraseñaTextField = new javax.swing.JTextField();
        tituloIniciarSesion4 = new javax.swing.JLabel();
        confirmarContraseñaTextField = new javax.swing.JTextField();
        tituloIniciarSesion5 = new javax.swing.JLabel();
        terminosCheckBox = new javax.swing.JCheckBox();
        crearCuentaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 29, 29));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloIniciarSesion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion.setText("Nombre de Usuario");
        jPanel2.add(tituloIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        tituloIniciarSesion1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 28)); // NOI18N
        tituloIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion1.setText("Registrar Cuenta");
        jPanel2.add(tituloIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        nombreUsuarioTextField.setBackground(new java.awt.Color(51, 51, 51));
        nombreUsuarioTextField.setColumns(50);
        nombreUsuarioTextField.setForeground(new java.awt.Color(204, 204, 204));
        nombreUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreUsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 304, 40));

        correoTextField.setBackground(new java.awt.Color(51, 51, 51));
        correoTextField.setColumns(50);
        correoTextField.setForeground(new java.awt.Color(204, 204, 204));
        correoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 304, 40));

        tituloIniciarSesion2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion2.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion2.setText("Correo Electronico");
        jPanel2.add(tituloIniciarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        tituloIniciarSesion3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion3.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion3.setText("Fecha de nacimiento");
        jPanel2.add(tituloIniciarSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        contraseñaTextField.setBackground(new java.awt.Color(51, 51, 51));
        contraseñaTextField.setColumns(50);
        contraseñaTextField.setForeground(new java.awt.Color(204, 204, 204));
        contraseñaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(contraseñaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 304, 40));

        tituloIniciarSesion4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion4.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion4.setText("Contraseña");
        jPanel2.add(tituloIniciarSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, -1, -1));

        confirmarContraseñaTextField.setBackground(new java.awt.Color(51, 51, 51));
        confirmarContraseñaTextField.setColumns(50);
        confirmarContraseñaTextField.setForeground(new java.awt.Color(204, 204, 204));
        confirmarContraseñaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarContraseñaTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(confirmarContraseñaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 750, 304, 43));

        tituloIniciarSesion5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tituloIniciarSesion5.setForeground(new java.awt.Color(255, 255, 255));
        tituloIniciarSesion5.setText("Confirmar Contraseña");
        jPanel2.add(tituloIniciarSesion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 730, -1, -1));

        terminosCheckBox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        terminosCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        terminosCheckBox.setText("Acepto los terminos y condiciones");
        terminosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminosCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(terminosCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 810, -1, -1));

        crearCuentaBtn.setBackground(new java.awt.Color(204, 0, 204));
        crearCuentaBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaBtn.setText("Crear Cuenta");
        crearCuentaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(crearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 840, 304, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-374046.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 322));

        datePicker1.setBackground(new java.awt.Color(51, 51, 51));
        datePicker1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextFieldActionPerformed

    private void correoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTextFieldActionPerformed

    private void contraseñaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaTextFieldActionPerformed

    private void confirmarContraseñaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarContraseñaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarContraseñaTextFieldActionPerformed

    private void terminosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminosCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminosCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarioDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarUsuarioDlg dialog = new RegistrarUsuarioDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmarContraseñaTextField;
    private javax.swing.JTextField contraseñaTextField;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JButton crearCuentaBtn;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreUsuarioTextField;
    private javax.swing.JCheckBox terminosCheckBox;
    private javax.swing.JLabel tituloIniciarSesion;
    private javax.swing.JLabel tituloIniciarSesion1;
    private javax.swing.JLabel tituloIniciarSesion2;
    private javax.swing.JLabel tituloIniciarSesion3;
    private javax.swing.JLabel tituloIniciarSesion4;
    private javax.swing.JLabel tituloIniciarSesion5;
    // End of variables declaration//GEN-END:variables
}
