
package com.equipo7.presentacion.gui.paneles;

//import com.equipo7.negocio.dtos.AlbumDTO;

/**
 * Muestra la miniatura del album, el nombre del album y el de su actor.
 * @author neri
 */
public class AlbumPanel extends javax.swing.JPanel {

    //private AlbumDTO album;
    
    /**
     * Creates new form ArtistaPanel
     */
    public AlbumPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPanel = new javax.swing.JPanel();
        nombreArtistaLbl = new javax.swing.JLabel();
        generoLbl = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setMaximumSize(new java.awt.Dimension(150, 220));
        setMinimumSize(new java.awt.Dimension(150, 220));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(150, 220));

        imagenPanel.setMaximumSize(new java.awt.Dimension(186, 145));
        imagenPanel.setMinimumSize(new java.awt.Dimension(186, 145));
        imagenPanel.setPreferredSize(new java.awt.Dimension(186, 145));

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        nombreArtistaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreArtistaLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreArtistaLbl.setText("Nombre del Album");
        nombreArtistaLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        generoLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoLbl.setForeground(new java.awt.Color(153, 153, 153));
        generoLbl.setText("Anio de publicacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreArtistaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(generoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreArtistaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel generoLbl;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JLabel nombreArtistaLbl;
    // End of variables declaration//GEN-END:variables
}
