
package com.equipo7.presentacion.gui.paneles;

/**
 *
 * @author neri
 */
public class CancionAlbumPanel extends javax.swing.JPanel {

    //private IUsuariosBO usuariosBO;
    
    //private CancionDTO cancionDTO;
    
    /**
     * Creates new form CancionAlbum
     */
    public CancionAlbumPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloCancionLbl = new javax.swing.JLabel();
        agregarAFavoritosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tituloCancionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tituloCancionLbl.setText("Nombre de la cancion");

        agregarAFavoritosBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agregarAFavoritosBtn.setText("+");
        agregarAFavoritosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAFavoritosBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloCancionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(agregarAFavoritosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCancionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarAFavoritosBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAFavoritosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAFavoritosBtnActionPerformed
        //usuariosBO.agregarCancionAFavoritos(this.cancion);
    }//GEN-LAST:event_agregarAFavoritosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAFavoritosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tituloCancionLbl;
    // End of variables declaration//GEN-END:variables
}
