
package com.equipo7.presentacion.gui.paneles;

import com.equipo7.negocio.dtos.CancionDTO;
import com.equipo7.negocio.dtos.UsuarioDTO;
import com.equipo7.presentacion.gui.PerfilUsuario;
import com.equipo7.presentacion.gui.estilo.Estilo;

/**
 *
 * @author neri
 */
public class CancionAlbumPanel extends javax.swing.JPanel {

    private UsuarioDTO usuarioDTO = PerfilUsuario.getUsuario();
    private CancionDTO cancionDTO;
    
    //private IUsuariosBO usuariosBO;
    
    //private CancionDTO cancionDTO;
    
    private Integer posicionLista;
    
    /**
     * Creates new form CancionAlbum
     * @param cancion
     */
    public CancionAlbumPanel(Integer posicion, CancionDTO cancion) {
        initComponents();
        
        this.cancionDTO = cancion;
        this.posicionLista = posicion;
        
        this.mostrarInformacionCancion();
        this.actualizarBotonAnadirAFavoritos();
    }
    
    
    private void mostrarInformacionCancion() {
        this.nombreCancionLbl.setText(this.cancionDTO.getNombre());
        
        if (this.usuarioDTO.getCancionesFavoritas().contains(this.cancionDTO)) {
            this.agregarFavoritosBtn.setBackground(Estilo.colorPrimario);
        } else {
            this.agregarFavoritosBtn.setBackground(Estilo.colorBaseFondo);
        }
        
        this.numeroCancionListaLbl.setText(String.format("%d.", this.posicionLista));
        this.nombreCancionLbl.setText(this.cancionDTO.getNombre());
        this.actualizarBotonAnadirAFavoritos();
    }
    
    public void actualizarBotonAnadirAFavoritos() {
        if (this.usuarioDTO.cancionEnFavoritos(cancionDTO)) {
            this.agregarFavoritosBtn.setBackground(Estilo.colorPrimario);
        } else {
            this.agregarFavoritosBtn.setBackground(Estilo.colorBaseFondo);
        }
    }
    
    /**
     * 
     */
    public void toggleMarcaComoFavorito() {
        if (this.usuarioDTO.cancionEnFavoritos(cancionDTO)) {
            this.usuarioDTO.eliminarCancionDeFavoritos(cancionDTO);
            this.agregarFavoritosBtn.setBackground(Estilo.colorBaseFondo);
        } else {
            this.usuarioDTO.agregarCancionAFavoritos(cancionDTO);
            this.agregarFavoritosBtn.setBackground(Estilo.colorPrimario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCancionLbl = new javax.swing.JLabel();
        agregarFavoritosBtn = new javax.swing.JButton();
        numeroCancionListaLbl = new javax.swing.JLabel();

        nombreCancionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nombreCancionLbl.setText("Nombre de la cancion");

        agregarFavoritosBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agregarFavoritosBtn.setText("+");
        agregarFavoritosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFavoritosBtnActionPerformed(evt);
            }
        });

        numeroCancionListaLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        numeroCancionListaLbl.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(numeroCancionListaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreCancionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarFavoritosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCancionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarFavoritosBtn)
                    .addComponent(numeroCancionListaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarFavoritosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFavoritosBtnActionPerformed
        this.toggleMarcaComoFavorito();
    }//GEN-LAST:event_agregarFavoritosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarFavoritosBtn;
    private javax.swing.JLabel nombreCancionLbl;
    private javax.swing.JLabel numeroCancionListaLbl;
    // End of variables declaration//GEN-END:variables
}
