/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.equipo7.presentacion.gui.paneles;

import java.awt.FlowLayout;
import java.awt.Frame;

/**
 * Frame utilizado para mostrar elementos en linea, en donde si el elemento siguiente
 * sobre pasa el ancho del panel se muestra en la parte de abajo.
 * 
 * Se utilizara para mostrar micro-paneles de artistas y albumes.
 * @author neri
 */
public class PanelResultadosFlexible extends javax.swing.JPanel {

    /**
     * Creates new form PanelResultadosFlexible
     */
    public PanelResultadosFlexible() {
        initComponents();
        this.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
